Feat/date picker
Albedo-13/datepicker-lib pull request #2
Opened 2024-04-23 09:53 UTC by Albedo-13

📍 Clickup task: https://app.clickup.com/t/86bycpdty

![image](https://github.com/Albedo-13/datepicker-lib/assets/42911311/67ecb782-74c1-4430-a229-5cdc75b7980b)

2024-04-23 17:26 UTC, ilyaAzarenko requested changes

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/assets/Clear.tsx
Лучше использовать импорт svg из файла как ReactComponent

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/components/calendar-body/calendar-body.tsx
> +import * as S from "./styles";
Используй именованный экспорт

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/components/calendar-body/styles.ts
> +  font-weight: 600;
Значения из темы должны приходить

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/components/date-picker/date-picker.tsx
> +type DatePickerProps = {
Интерфейс

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/components/input/styles.ts
> +export { Input, InputButtonLeft, InputButtonRight, InputWrapper };
экспортируй на месте
`export const Input = ....`

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/types/calendar.ts
> +  fromRange: Date | null;
`fromRange?: Date`

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/types/input.ts
> +  handleInputClear: () => void,
`handleInputClear: VoidFunction`

2024-04-23 17:26 UTC, ilyaAzarenko commented on src/utils/dateUtils.ts
> +    weekdayOfCurrentMonthStart === 0 ? 7 : weekdayOfCurrentMonthStart;
Магические цифры

2024-04-24 19:09 UTC, Albedo-13 commented on src/assets/Clear.tsx
Не вышло, пока оставил как есть

2024-04-24 19:31 UTC, ilyaAzarenko approved these changes

2024-04-25 06:29 UTC, merged